<?xml version="1.0" encoding="utf-8"?><Database Name="InfoDB" Class="InfoDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\InfoDB.mdf;Integrated Security=True" SettingsObjectName="SMS.My.MySettings" SettingsPropertyName="InfoDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Users]" Member="Users">
    <Type Name="Users">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[[Full Name]]]" Member="_Full_Name_" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Picture" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Professors" Member="Professors">
    <Type Name="Professor">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[[Professor ID]]]" Member="_Professor_ID_" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[[Professor Name]]]" Member="_Professor_Name_" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Age" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Picture" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[[Phone Number]]]" Member="_Phone_Number_" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[[Email]]]" Member="_Email_" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Students" Member="Students">
    <Type Name="Students">
      <Column Name="STUDENTINF" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Age" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ContactNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StudentID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmailAddress" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Class" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Stream" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StudentPicture" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Courses" Member="Courses">
    <Type Name="Course">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StudentName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Class" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Course" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Exam" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Overall" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GPA" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Grade" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>